os:
  - linux
  - osx
sudo: false
language: c

install:
  - PATH="`npm bin`:`npm bin -g`:$PATH"
  # Install dependencies and build
  - npm install

script:
  # Output useful info for debugging
  - node --version
  - npm --version
  - npm run lint
  # TODO: fetch shadow-node headers to build
  # - npm run build
  # Run tests
  # TODO: add tests
  # - npm test
